---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-image
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  resources:
    limits:
      cpu: 1000
      memory: 1024Mi
  commands:
  # wait for docker service to be up before running docker build
  - /usr/local/bin/wait
  - docker build -t gitlab:$${DRONE_COMMIT_SHA} .
  when:
    event:
    - pull_request
    - tag
    - push

- name: scan-image
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
  resources:
    limits:
      cpu: 1000
      memory: 1024Mi
  pull: always
  environment:
    IMAGE_NAME: gitlab:${DRONE_COMMIT_SHA}
    FAIL_ON_DETECTION: false
    TRIVY_SKIP_FILES: /etc/keys/key
  when:
    event:
      exclude:
        - tag

- name: deploy_image
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - if [[ "$${DRONE_BRANCH}" == "master" ]] || [[ -n "$${DRONE_TAG}" ]]; then
    docker login -u="$${REGISTRY_USER}" -p="$${DOCKER_PASSWORD}" $${REPO};
    docker tag gitlab:$${DRONE_COMMIT_SHA} $${REPO}/$${AUTHOR}/$${NAME}:$${DRONE_TAG:-latest};
    docker push $${REPO}/$${AUTHOR}/$${NAME}:$${DRONE_TAG:-latest};
    fi
  environment:
    AUTHOR: ukhomeofficedigital
    DOCKER_PASSWORD:
      from_secret: docker_password
    NAME: docker-gitlab
    REGISTRY_USER: ukhomeofficedigital+gitlab
    REPO: quay.io
  when:
    event:
    - tag

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  resources:
    limits:
      cpu: 1000
      memory: 1024Mi