pipeline:
  building_image:
    image: docker:17.07.0
    environment:
    - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
    - docker build -t gitlab:$${DRONE_BUILD_NUMBER} .
    when:
      event: [pull_request, tag, push]

  deploy_image:
    image: docker:17.07.0
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - NAME=docker-gitlab
      - REPO=quay.io
      - AUTHOR=ukhomeofficedigital
      - REGISTRY_USER=ukhomeofficedigital+gitlab
    commands:
      - if [[ "$${DRONE_BRANCH}" == "master" ]] || [[ -n "$${DRONE_TAG}" ]]; then
        docker login -u="$${REGISTRY_USER}" -p=$${DOCKER_PASSWORD} $${REPO};
        docker tag gitlab:$${DRONE_BUILD_NUMBER} $${REPO}/$${AUTHOR}/$$NAME}:$${DRONE_TAG:-latest};
        docker push $${REPO}/$${AUTHOR}/$${NAME}:$${DRONE_TAG:-latest};
        fi
