---
apiVersion: v1
kind: ReplicationController
metadata:
  name: gitlab
  labels:
    name: gitlab
spec:
  replicas: 1
  selector:
    name: gitlab
  template:
    metadata:
      labels:
        name: gitlab
    spec:
      containers:
      - name: vault-sidekick
        image: quay.io/ukhomeofficedigital/vault-sidekick:v0.0.5
        args:
          - -logtostderr=true
          - -v=4
          - -tls-skip-verify=true
          - -auth=/etc/vault/vault.yml
          - -output=/etc/secrets
          - -cn=secret:platform/platform_tls/platform_tls:fmt=cert,file=platform_tls
          - -cn=secret:gitlab/secrets/gitlab.env:fmt=env,file=gitlab.env
          - -cn=secret:gitlab/secrets/dhparams.pem:fmt=txt,file=dhparams.pem
        env:
          - name: VAULT_ADDR
            value: https://vault.vault.svc.cluster.local:8200
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
        - name: vault
          mountPath: /etc/vault
      - name: gitlab
        image: quay.io/ukhomeofficedigital/docker-gitlab:v8.5.5-rc2
        ports:
        - containerPort: 22
        - containerPort: 80
        - containerPort: 443
        env:
        - name: DEBUG
          value: "true"
        - name: DB_TYPE
          value: mysql
        - name: DB_HOST
          value: 127.0.0.1
        - name: DB_NAME
          value: gitlabhq
        - name: DB_USER
          value: admin
        - name: GITLAB_ENV_FILE
          value: /etc/secrets/gitlab.env
        - name: REDIS_HOST
          value: 127.0.0.1
        - name: GITLAB_HOST
          value: gitlab.digital.homeoffice.gov.uk
        - name: GITLAB_PORT
          value: "443"
        - name: GITLAB_SSH_PORT
          value: "2222"
        - name: GITLAB_SHELL_SSH_PORT
          value: "2222"
        - name: REDIS_PORT
          value: "6379"
        - name: GITLAB_EMAIL
          value: gitlab@digital.homeoffice.gov.uk
        - name: GITLAB_KMS_BACKUPS
          value: daily
        - name: GITLAB_KMS_BACKUP_TIME
          value: '*/2:00'
        - name: GITLAB_BACKUP_DIR
          value: /home/git/data/backups
        - name: GITLAB_KMS_BACKUP_TIME
          value: '*/2:00'
        - name: AWS_BACKUP_FILTER
          value: "*_gitlab_backup.tar"
        - name: SMTP_HOST
          value: email-smtp.eu-west-1.amazonaws.com
        - name: SMTP_PORT
          value: "465"
        - name: SMTP_DOMAIN
          value: digital.homeoffice.gov.uk
        - name: SMTP_TLS
          value: "true"
        - name: SMTP_STARTTLS
          value: "false"
        - name: GITLAB_HTTPS
          value: "true"
        - name: SSL_CERTIFICATE_PATH
          value: /etc/secrets/platform_tls.crt
        - name: SSL_KEY_PATH
          value: /etc/secrets/platform_tls.key
        - name: SSL_DHPARAM_PATH
          value: /etc/secrets/dhparams.pem
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
        - name: gitlab-data
          mountPath: /home/git/data
      - name: redis
        image: redis
      - name: gitlab-mysql
        image: tutum/mysql
        env:
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASS
          value: PASSWORD
        - name: ON_CREATE_DB
          value: gitlabhq
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: gitlab-db
      volumes:
      - name: vault
        secret:
          secretName: vault
      - name: secrets
        emptyDir: {}
      - name: gitlab-data
        rbd:
          fsType: xfs
          image: data_gitlab
          monitors:
          - 10.41.30.100:6789
          - 10.41.31.100:6789
          - 10.41.32.100:6789
          pool: rbd
          keyring: ""
          secretRef:
            name: ceph-secret
          user: admin
      - name: gitlab-db
        rbd:
          fsType: xfs
          image: mysql_gitlab
          monitors:
          - 10.41.30.100:6789
          - 10.41.31.100:6789
          - 10.41.32.100:6789
          pool: rbd
          keyring: ""
          secretRef:
            name: ceph-secret
          user: admin
