---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  replicas: 1
  selector:
    name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - name: gitlab-mysql
        image: tutum/mysql
        env:
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASS
          value: l4KWcSuBi5AC9LDdFE3jc2Se
        - name: ON_CREATE_DB
          value: gitlabhq
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: gitlab-db
      ports:
      - containerPort: 3306
      volumes:
      - name: gitlab-db
        rbd:
          fsType: xfs
          image: db_gitlab
          monitors:
          - 10.41.30.100:6789
          - 10.41.31.100:6789
          - 10.41.32.100:6789
          pool: rbd
          keyring: ""
          secretRef:
            name: ceph-secret
          user: admin
