apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    name: gitlab
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30490
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 30491
    port: 443
    protocol: TCP
    targetPort: 443
  - name: ssh
    nodePort: 30492
    port: 2222
    protocol: TCP
    targetPort: 22
  selector:
    name: gitlab
